### ISSUE TITLE
Can it use the same libp2p instance as kubo? for example for an app that uses both IPFS and pubsub

### ISSUE THREAD

**Issue by estebanabaroa** [MichaelMure/ipfs-pubsub-service-api#3]
And doesn't want to have 2 libp2p instances to save on resources.

**Comment by MichaelMure** [comment]
I would think that this API could be integrated into kubo (if that makes sense for the maintainers). Otherwise, we'd bolt that on top of boxo or raw libp2p.

Short answer yes, but how exactly is left as an exercise.
