### ISSUE TITLE
Signatures should be exposed when reading messages

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/ipfs-pubsub-service-api#4]
With current libp2p pubsub, crypto signature are attached to each message. The pubsub client check those (depending on the policy, yet enabled by default in go).

To avoid having the client of this new API having to trust the server-side, we should expose said signature along the message, so that the client can optionally check it. Likely, that also mean exposing the public key of the author, so that:
- client can compute pubkey-->peerID and verify they match
- client can compute sign(msg, pubkey) and verify the authenticity of the message

**Comment by MichaelMure** [comment]
Now, those can be heavy, so ... do we want to make that optional?

**Comment by PancakesArchitect** [comment]
I'd say that checking the message signature should be optional. But instead of a per-message signatures, there could be a public key verification when 2 peers first start exchanging on a topic, during the */join* API call ? And if successfull messages from this peer on that topic are assumed to be trustworthy.

**Comment by MichaelMure** [comment]
`/join` doesn't work well here. There might not be any peer yet on that topic, and new peer can join anytime after that.

It seems reasonable to have at least:
- no check, the client trust the server only get (message, peerID)
- full check, the client doesn't have to trust the server, get (message, peerID, pubkey, signature) and check everything

If I rephrase a bit what you are suggesting, there could be some middle ground where only the first message for that peer get fully checked. The problem I see in this is that if you care about the full chain of trust, it's to protect yourself **from a bad behavior of the server**, not really from the sender. If you can't trust the server, you can't trust it's doing the proper signature check. In that case, only checking the first signature for a given peer won't cut it, because then the server can lie to you on the next message.
